In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
from torchvision.transforms import Normalize
from collections import namedtuple
import torch.nn as nn

#importing Technical Analysis tools
from ta import trend
from ta import volatility
from ta import momentum

import utils
from utils import return_fun

In [2]:
reuters=pd.read_csv("data/reut_data.csv",sep='|')

sx5e_data=pd.read_csv("data\SX5E.csv")

In [3]:
sx5e_data = sx5e_data.sort_index(axis=0 ,ascending=False)
sx5e_data.reset_index(drop=True,inplace=True)
sx5e_data['Date']=pd.to_datetime(sx5e_data.Date)

sx5e_data.dropna(inplace=True)


adi=trend.ADXIndicator(close=sx5e_data[' Close'],high=sx5e_data[' High'],low=sx5e_data[' Low'])
m_acd=trend.MACD(close=sx5e_data[' Close'])

r_si=momentum.RSIIndicator(close=sx5e_data[' Close'])
stochastic_oscilator=momentum.StochasticOscillator(close=sx5e_data[' Close'],high=sx5e_data[' High'],low=sx5e_data[' Low'])
williamsr=momentum.WilliamsRIndicator(high=sx5e_data[' High'],low=sx5e_data[' Low'],close=sx5e_data[' Close'])

bollinger=volatility.BollingerBands(close=sx5e_data[' Close'])
atr=volatility.AverageTrueRange(high=sx5e_data[' High'],low=sx5e_data[' Low'],close=sx5e_data[' Close'])

exponential_moving_avarge9=trend.EMAIndicator(close=sx5e_data[' Close'],window=9)
exponential_moving_avarge18=trend.EMAIndicator(close=sx5e_data[' Close'],window=18)
exponential_moving_avarge30=trend.EMAIndicator(close=sx5e_data[' Close'],window=30)

sx5e_data['ADX']=adi.adx()
sx5e_data['MACD']=m_acd.macd()
sx5e_data['RSI']=r_si.rsi()
sx5e_data['Stoch Osc']=stochastic_oscilator.stoch()
sx5e_data['Williams R']=williamsr.williams_r()
sx5e_data['Bollinger High band']=bollinger.bollinger_hband()
sx5e_data['Bolinger Low Band']=bollinger.bollinger_lband()
sx5e_data['ATR']=atr.average_true_range()
sx5e_data['EMA9']=exponential_moving_avarge9.ema_indicator()
sx5e_data['EMA18']=exponential_moving_avarge18.ema_indicator()
sx5e_data['EMA30']=exponential_moving_avarge30.ema_indicator()
sx5e_data.dropna(inplace=True)
ret_fun=return_fun(sx5e_data,1,4)
sx_ret=sx5e_data.copy()
sx_ret['Ret']=ret_fun
sx_ret.drop(columns=['ADX','MACD','RSI','Stoch Osc','Williams R','Bollinger High band','Bolinger Low Band','ATR','EMA9','EMA18','EMA30',' Open',' High',' Low'],inplace=True)

c:\users\48694\appdata\local\programs\python\python39\lib\site-packages\ta\trend.py:768: RuntimeWarning: invalid value encountered in double_scalars
  dip[i] = 100 * (self._dip[i] / self._trs[i])
c:\users\48694\appdata\local\programs\python\python39\lib\site-packages\ta\trend.py:772: RuntimeWarning: invalid value encountered in double_scalars
  din[i] = 100 * (self._din[i] / self._trs[i])

In [4]:
reuters.drop(columns='column1',inplace=True)
reuters.drop_duplicates(subset ="Headline",
                     keep = 'first', inplace = True)
reuters.dropna(inplace=True)
reuters.reset_index(drop=True,inplace=True)

for i in range(len(reuters)):
    text=reuters['Headline'][i]
    text=text.replace("REFILE-UPDATE 2-","")
    text=text.replace("UPDATE 2-","")
    text=text.replace("UPDATE 1-","")
    text=text.replace("UPDATE ","")
    text=text.replace(",","")
    text=text.replace(".","")
    text=text.replace(";","")
    text=text.replace(":","")
    text=text.replace("-","")
    text=text.replace("European","")
    reuters['Headline'][i]=text

In [49]:
reuters['Date']=pd.to_datetime(reuters.Date)

In [73]:

lang=utils.Lang('t')

for i in range(len(reuters)):
    sentence=reuters['Headline'][i]
    lang.addSentence(sentence)

In [5]:
# sx5e_data.drop(columns='Date',inplace=True)
sx5e_data.drop(sx5e_data.tail(1).index,inplace=True)
# sx5e_tensor=torch.tensor(sx5e_data.values)

In [10]:
sx5e_data.tail()

,Date,Open,High,Low,Close,ADX,MACD,RSI,Stoch Osc,Williams R,Bollinger High band,Bolinger Low Band,ATR,EMA9,EMA18,EMA30
3100,2021-12-03,4118.98,4150.42,4059.02,4080.15,32.533720,-40.206056,36.052834,13.594636,-86.405364,4513.325492,4039.118508,63.487845,4162.426804,4213.740555,4227.572316
3101,2021-12-06,4095.39,4146.16,4078.64,4137.11,33.184024,-41.135771,42.302775,28.282620,-71.717380,4507.235731,4023.666269,63.775856,4157.363443,4205.674181,4221.736038
3102,2021-12-07,4157.72,4277.03,4157.72,4276.20,31.300793,-30.299898,54.099957,64.149046,-35.850954,4501.157655,4022.901345,69.214724,4181.130755,4213.097951,4225.249842
3103,2021-12-08,4273.32,4288.20,4233.09,4233.09,29.383481,-24.903930,50.643629,54.917354,-45.082646,4492.271221,4020.214779,68.207243,4191.522604,4215.202377,4225.755658
3104,2021-12-09,4242.66,4246.52,4201.85,4208.30,28.028969,-22.370065,48.716216,52.552518,-47.447482,4480.865796,4016.650204,66.526012,4194.878083,4214.475811,4224.629487

In [28]:
sx5e_data.head()

,Open,High,Low,Close,ADX,MACD,RSI,Stoch Osc,Williams R,Bollinger High band,Bolinger Low Band,ATR,EMA9,EMA18,EMA30
29,2715.33,2727.69,2653.84,2680.25,34.469302,-71.770257,33.565359,27.478230,-72.521770,2995.831363,2595.601637,55.491494,2714.461109,2769.853320,2820.010539
30,2700.85,2712.62,2657.39,2674.46,34.726002,-71.223066,33.079169,25.213485,-74.786515,2977.624736,2587.229264,55.472816,2706.460888,2759.811918,2810.620182
31,2688.23,2705.28,2676.85,2683.83,34.964365,-69.235232,34.726933,29.380893,-70.619107,2950.767307,2586.682693,53.711900,2701.934710,2751.813821,2802.440170
32,2702.23,2720.77,2676.49,2720.77,34.709250,-63.942026,40.904662,45.810354,-54.189646,2909.023979,2602.021021,53.038193,2705.701768,2748.546051,2797.171127
33,2743.95,2779.29,2736.31,2762.25,32.930601,-55.757298,46.973611,64.259029,-35.740971,2883.103078,2612.706922,53.429751,2717.011414,2749.988572,2794.918151

In [13]:
sx5e_data[sx5e_data['Date']=='2019-01-01']

,Date,Open,High,Low,Close,ADX,MACD,RSI,Stoch Osc,Williams R,Bollinger High band,Bolinger Low Band,ATR,EMA9,EMA18,EMA30
2347,2019-01-01,3001.42,3001.42,3001.42,3001.42,34.993277,-45.63149,40.936934,42.260711,-57.739289,3139.922661,2924.446339,38.14759,2997.363856,3027.223818,3064.002687

In [15]:
sx5e_data[sx5e_data['Date']=='2020-01-02']

,Date,Open,High,Low,Close,ADX,MACD,RSI,Stoch Osc,Williams R,Bollinger High band,Bolinger Low Band,ATR,EMA9,EMA18,EMA30
2606,2020-01-02,3754.24,3801.13,3754.24,3793.24,20.227914,27.659024,63.953279,94.427966,-5.572034,3824.978029,3622.345971,32.149592,3760.56026,3740.938644,3718.808214

In [19]:
sx5e_data[sx5e_data['Date']=='2021-01-04']

,Date,Open,High,Low,Close,ADX,MACD,RSI,Stoch Osc,Williams R,Bollinger High band,Bolinger Low Band,ATR,EMA9,EMA18,EMA30
2863,2021-01-04,3565.68,3609.91,3548.31,3564.39,21.043001,33.085616,58.826558,78.196101,-21.803899,3597.258266,3470.898734,42.762175,3552.208421,3534.16206,3502.452129

In [20]:
ret_fun.remove(None)
tensor_ret=torch.tensor(ret_fun,dtype=torch.float32)
mean_ret=torch.mean(tensor_ret)
std_ret=torch.std(tensor_ret)

In [23]:
sx5e_data.drop(columns='Date',inplace=True)
# sx5e_data.drop(sx5e_data.tail(1).index,inplace=True)
sx5e_tensor=torch.tensor(sx5e_data.values)

In [24]:
mean=torch.mean(sx5e_tensor,dim=0)
std=torch.std(sx5e_tensor,dim=0)
sx5e_norm=(sx5e_tensor-mean)/std
print(sx5e_norm)

tensor([[-0.9221, -0.9442, -1.0001,  ..., -0.9280, -0.8126, -0.7074],
        [-0.9531, -0.9766, -0.9926,  ..., -0.9452, -0.8345, -0.7281],
        [-0.9801, -0.9924, -0.9511,  ..., -0.9550, -0.8519, -0.7462],
        ...,
        [ 2.1637,  2.3829,  2.2003,  ...,  2.2373,  2.3354,  2.4011],
        [ 2.4110,  2.4069,  2.3607,  ...,  2.2597,  2.3400,  2.4022],
        [ 2.3454,  2.3174,  2.2942,  ...,  2.2670,  2.3384,  2.3997]],
       dtype=torch.float64)

In [21]:
sx_ret.dropna(inplace=True)

In [71]:
sx_ret.head()

         Date    Close       Ret
29 2010-02-11  2680.25 -0.216025
30 2010-02-12  2674.46  0.350351
31 2010-02-15  2683.83  1.376391
32 2010-02-16  2720.77  1.524568
33 2010-02-17  2762.25  0.581048

In [26]:
sx5e_norm.shape

torch.Size([3076, 15])

In [35]:
sx_ret[sx_ret['Date']=='2019-01-01']

           Date    Close       Ret
2347 2019-01-01  3001.42 -0.274537

In [40]:
sx_ret['Date'][30]

Timestamp('2010-02-12 00:00:00')

In [33]:
sx5e_tensor[2318]

tensor([3001.4200, 3001.4200, 3001.4200, 3001.4200,   34.9933,  -45.6315,
          40.9369,   42.2607,  -57.7393, 3139.9227, 2924.4463,   38.1476,
        2997.3639, 3027.2238, 3064.0027], dtype=torch.float64)

In [95]:
date=sx_ret['Date'][3104]
headline=reuters[reuters['Date']==date].iloc[0]
print(headline['Headline'])
print(sx_ret['Ret'][3104])
print(date)

 shares fall again on Omicron worries
-0.2171898391274464
2021-12-09 00:00:00

In [134]:
d=namedtuple('d',['headline','numeric'])
data=namedtuple('Data',['data','target'])

test_set_2019=[]
test_set_2020=[]
test_set_2021=[]


for i in range(2348,2606):
    date=sx_ret['Date'][i]
    headline=reuters[reuters['Date']==date]
    if(headline.empty):
        continue
    headline=headline.iloc[0]
    headline=utils.tensorFromSentence(lang,headline['Headline'])
    numeric=sx5e_norm[i-27-5 : i-27]
    ret=sx_ret['Ret'][i]
    ret=torch.tensor(ret)
    r=(ret-mean_ret)/std_ret
    d1=d(headline,numeric)
    da=data(d1,r)
    test_set_2019.append(da)

for i in range(2606,2863):
    date=sx_ret['Date'][i]
    headline=reuters[reuters['Date']==date]
    if(headline.empty):
        continue
    headline=headline.iloc[0]
    headline=utils.tensorFromSentence(lang,headline['Headline'])
    numeric=sx5e_norm[i-27-5 : i-27]
    ret=sx_ret['Ret'][i]
    ret=torch.tensor(ret)
    r=(ret-mean_ret)/std_ret
    d1=d(headline,numeric)
    da=data(d1,r)
    test_set_2020.append(da)
    
for i in range(2863,3103):
    date=sx_ret['Date'][i]
    headline=reuters[reuters['Date']==date]
    if(headline.empty):
        continue
    headline=headline.iloc[0]
    headline=utils.tensorFromSentence(lang,headline['Headline'])
    numeric=sx5e_norm[i-27-5 : i-27]
    ret=sx_ret['Ret'][i]
    ret=torch.tensor(ret)
    r=(ret-mean_ret)/std_ret
    d1=d(headline,numeric)
    da=data(d1,r)
    test_set_2021.append(da)

In [135]:
print(len(test_set_2019))
print(len(test_set_2020))
print(len(test_set_2021))
print(sx5e_norm[3075])
print(test_set_2021[-1])

239
257
240
tensor([ 2.3454,  2.3174,  2.2942,  2.2692,  0.7009, -0.6385, -0.3357, -0.1934,
        -0.1934,  2.6695,  2.0910,  1.1603,  2.2670,  2.3384,  2.3997],
       dtype=torch.float64)
Data(data=d(headline=tensor([12, 39, 40,  0, 14, 41,  8, 42, 43, 44, 45, 46]), numeric=tensor([[ 2.1637,  2.1267,  2.0494,  2.0549,  1.1773, -0.8958, -1.2846, -1.2070,
         -1.2070,  2.7378,  2.2006,  0.8563,  2.2413,  2.3711,  2.4287],
        [ 2.0808,  2.1110,  1.9903,  1.9953,  1.2650, -1.0855, -1.4485, -1.4363,
         -1.4363,  2.7402,  2.1385,  0.9822,  2.1969,  2.3368,  2.4062],
        [ 2.0304,  2.1019,  2.0320,  2.1170,  1.3464, -1.1088, -0.8993, -0.9677,
         -0.9677,  2.7269,  2.1058,  0.9991,  2.1860,  2.3192,  2.3933],
        [ 2.1637,  2.3829,  2.2003,  2.4142,  1.1106, -0.8372,  0.1374,  0.1765,
          0.1765,  2.7137,  2.1042,  1.3180,  2.2373,  2.3354,  2.4011],
        [ 2.4110,  2.4069,  2.3607,  2.3221,  0.8705, -0.7020, -0.1663, -0.1180,
         -0.1180,  2.6943,  2.0985,  1.2589,  2.2597,  2.3400,  2.4022]],
       dtype=torch.float64)), target=tensor(-0.8024, dtype=torch.float64))

In [136]:
test_loader_2019=torch.utils.data.DataLoader(test_set_2019, batch_size=1)
test_loader_2020=torch.utils.data.DataLoader(test_set_2020, batch_size=1)
test_loader_2021=torch.utils.data.DataLoader(test_set_2021, batch_size=1)

In [153]:

def hit_profit(output, target, std_ret,mean_ret):
    o=output.flatten()*std_ret +mean_ret
    t=target*std_ret + mean_ret
    tmp=o*t
    hit_profit=0
    for i in range(len(tmp)):
        if(tmp[i].item() > 0):
            hit_profit+=torch.abs(target[i])
    return hit_profit

In [137]:
from utils import TextAndNumeric
from utils import TextAndNumeric
from utils import TextAndNumeric

In [148]:
from utils import hit_profit
from utils import correct

ImportError: cannot import name 'hit_profit' from 'utils' (G:\Nauczanie_maszynowe\Projekt\utils.py)

In [237]:
tan=torch.load('models/text_and_numeric')

In [223]:
loss_fn=torch.nn.MSELoss()

tan.eval()
with torch.no_grad():
        val_loss_buffer=[]
        val_ac=0
        cor=0
        hit_profit=0
        for i, (x,y) in enumerate(test_loader_2019):
            headline,numeric = x
            numeric=numeric.float()
            headline=headline.cuda()
            numeric=numeric.cuda()
            y=y.cuda()
            
            output=model(headline,numeric)
            output.float()
            y.float()
            val_loss_buffer.append(loss_fn(output,y).item())
            if(correct(output, y, std_ret, mean_ret)==1):
                hit_profit += correct(output, y, std_ret, mean_ret) * abs(y*std_ret - mean_ret)
            else:
                hit_profit-= abs(y*std_ret - mean_ret)
            
            cor+=correct(output,y,std_ret,mean_ret)
            
        val_acc=cor/len(test_loader_2019)
        val_loss=torch.mean(torch.tensor(val_loss_buffer))
        print(f"Test loss: {val_loss:.3f} Test Acc {val_acc:.5f}")
        print(hit_profit)

Test loss: 0.425 Test Acc 0.41004
tensor([-3.8817], device='cuda:0', dtype=torch.float64)

In [230]:
def test_tan(model,loader):
    loss_fn=torch.nn.MSELoss()

    tan.eval()
    with torch.no_grad():
        val_loss_buffer=[]
        val_ac=0
        cor=0
        hit_profit=0
        for i, (x,y) in enumerate(loader):
            headline,numeric = x
            numeric=numeric.float()
            headline=headline.cuda()
            numeric=numeric.cuda()
            y=y.cuda()
            
            output=model(headline,numeric)
            output.float()
            y.float()
            val_loss_buffer.append(loss_fn(output,y).item())
            if(correct(output, y, std_ret, mean_ret)==1):
                hit_profit += correct(output, y, std_ret, mean_ret) * abs(y*std_ret - mean_ret)
            else:
                hit_profit-= abs(y*std_ret - mean_ret)
            
            cor+=correct(output,y,std_ret,mean_ret)
            
        val_acc=cor/len(loader)
        val_loss=torch.mean(torch.tensor(val_loss_buffer))
        print(f"Test loss: {val_loss:.3f} Test Acc {val_acc:.5f}")
        print(f"Test Hit Profit: {hit_profit.item():0.3f}")
        
        return val_loss,val_acc,hit_profit

In [234]:
def test_text(model,loader):
    loss_fn=torch.nn.MSELoss()

    model.eval()
    with torch.no_grad():
        val_loss_buffer=[]
        val_ac=0
        cor=0
        hit_profit=0
        for i, (x,y) in enumerate(loader):
            headline,numeric = x
            headline=headline.cuda()
            y=y.cuda()
            
            output=model(headline)
            output.float()
            y.float()
            val_loss_buffer.append(loss_fn(output,y).item())
            if(correct(output, y, std_ret, mean_ret)==1):
                hit_profit += correct(output, y, std_ret, mean_ret) * abs(y*std_ret - mean_ret)
            else:
                hit_profit-= abs(y*std_ret - mean_ret)
            
            cor+=correct(output,y,std_ret,mean_ret)
            
        val_acc=cor/len(loader)
        val_loss=torch.mean(torch.tensor(val_loss_buffer))
        print(f"Test loss: {val_loss:.3f} Test Acc {val_acc:.5f}")
        print(f"Test Hit Profit: {hit_profit.item():0.3f}")
        
        return val_loss,val_acc,hit_profit

In [235]:
def test_numeric(model,loader):
    loss_fn=torch.nn.MSELoss()

    model.eval()
    with torch.no_grad():
        val_loss_buffer=[]
        val_ac=0
        cor=0
        hit_profit=0
        for i, (x,y) in enumerate(loader):
            headline,numeric = x
            numeric=numeric.float()
            numeric=numeric.cuda()
            y=y.cuda()
            
            output=model(numeric)
            output.float()
            y.float()
            val_loss_buffer.append(loss_fn(output,y).item())
            if(correct(output, y, std_ret, mean_ret)==1):
                hit_profit += correct(output, y, std_ret, mean_ret) * abs(y*std_ret - mean_ret)
            else:
                hit_profit-= abs(y*std_ret - mean_ret)
            
            cor+=correct(output,y,std_ret,mean_ret)
            
        val_acc=cor/len(loader)
        val_loss=torch.mean(torch.tensor(val_loss_buffer))
        print(f"Test loss: {val_loss:.3f} Test Acc {val_acc:.5f}")
        print(f"Test Hit Profit: {hit_profit.item():0.3f}")
        
        return val_loss,val_acc,hit_profit

In [242]:
test_tan(model,test_loader_2021)

Test loss: 0.551 Test Acc 0.42083
Test Hit Profit: -7.666

(tensor(0.5513),
 0.42083333333333334,
 tensor([-7.6655], device='cuda:0', dtype=torch.float64))

In [ ]:
loss_fn=torch.nn.MSELoss()

model.eval()
with torch.no_grad():
        val_loss_buffer=[]
        val_ac=0
        cor=0
        hit_profit=0
        for i, (x,y) in enumerate(test_loader_2019):
            headline,numeric = x
            numeric=numeric.float()
            headline=headline.cuda()
            numeric=numeric.cuda()
            y=y.cuda()
            
            output=model(headline,numeric)
            output.float()
            y.float()
            val_loss_buffer.append(loss_fn(output,y).item())
            if(correct(output, y, std_ret, mean_ret)==1):
                hit_profit += correct(output, y, std_ret, mean_ret) * abs(y*std_ret - mean_ret)
            else:
                hit_profit-= abs(y*std_ret - mean_ret)
            
            cor+=correct(output,y,std_ret,mean_ret)
            
        val_acc=cor/len(test_loader_2019)
        val_loss=torch.mean(torch.tensor(val_loss_buffer))
        print(f"Test loss: {val_loss:.3f} Test Acc {val_acc:.5f}")
        print(hit_profit)